version: '3'
name: mongo
services:
  mongodb:
    image: mongodb/mongodb-community-server
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./DB/mongo_data:/data/db
      - ./DB/mongo_config:/data/configdb